framework:
    messenger:
        default_bus: command.bus

        buses:
            command.bus:
                middleware:
                    - doctrine_transaction
            query.bus:
                middleware:
                    - doctrine_transaction

        transports:
            sync: 'sync://'
            async: '%env(MESSENGER_TRANSPORT_DSN)%'

        routing:
            'App\Domain\Card\Command\AddCardCommand': sync
            'App\Domain\Card\Query\GetCardQuery': sync