framework:
    messenger:
        default_bus: command.bus

        buses:
            command.bus:
                middleware:
                    - doctrine_transaction
            query.bus: ~
            event.bus:
                default_middleware: allow_no_handlers

        transports:
            sync: 'sync://'
            async:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                retry_strategy:
                    delay: 2000
                    max_retries: 3

        routing:
            'App\Infrastructure\Common\Query\Query': sync
            'App\Infrastructure\Common\Command\Command': async
            'App\Infrastructure\Common\Event\Event': async