version: '3'
services:
  php:
    build:
      context: ./docker/php
    ports:
      - 9002:9000
    volumes:
      - ./:/var/www/html
      - ./docker/php/www.conf:/usr/local/etc/php-fpm.d/www.conf
    environment:
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}

  nginx:
    image: nginx:1.21.1-alpine
    ports:
      - 8888:80
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./docker/nginx/fastcgi-php.conf:/etc/nginx/snippets/fastcgi-php.conf
      - ./docker/nginx/log:/var/log/nginx
    depends_on:
      - php

  mysql:
    image: mysql:8.0.26
    ports:
      - 3307:3306
    depends_on:
      - php
    volumes:
      - ./docker/mysql/data:/var/lib/mysql
      - ./docker/mysql/init:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}