App\Domain\Deck\DeckAddDTO:
  properties:
    id:
      - NotBlank: { message: "Deck id can't be empty" }
      - Uuid: { message: "Deck id is invalid Uuid type" }
    user_id:
      - NotBlank: { message: "User id can't be empty" }
      - Uuid:  { message: "User id is invalid Uuid type" }

App\Domain\Deck\DeckGetDTO:
  properties:
    id:
      - NotBlank: { message: "Deck id can't be empty" }
      - Uuid: { message: "Deck id is invalid Uuid type" }

App\Domain\Deck\Card\DeckCardDTO:
  properties:
    deck_id:
      - NotBlank: { message: "Deck id can't be empty" }
      - Uuid: { message: "Deck id is invalid Uuid type" }
    card_id:
      - NotBlank: { message: "Card id can't be empty" }
      - Uuid:  { message: "Card id is invalid Uuid type" }
    amount:
      - NotBlank: { message: "Card amount can't be empty" }
      - PositiveOrZero: { message: "Card amount can't be negative" }
      - LessThanOrEqual:
          value: 2
          message: "Card amount can't be more than 2"

App\Domain\Card\CardDTO:
  properties:
    id:
      - NotBlank: { message: "Card id can't be empty" }
      - Uuid: { message: "Card id is invalid Uuid type" }
    title:
      - NotBlank: { message: "Card title can't be empty" }
      - Length:
          min: 2
          max: 255
          minMessage: 'Card title minimum length is {{ limit }} characters'
          maxMessage: 'Card title maximum length is {{ limit }} characters'
    power:
      - NotBlank: { message: "Card power can't be empty" }
      - PositiveOrZero: { message: "Card power can't be negative or 0" }
      - LessThan:
          value: 65535
          message: "Card power can't be more than 65535"