# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    _instanceof:
        App\Infrastructure\Common\Command\CommandHandler:
            tags:
                - { name: messenger.message_handler, bus: command.bus }
        App\Infrastructure\Common\Query\QueryHandler:
            tags:
                - { name: messenger.message_handler, bus: query.bus }

    App\Infrastructure\Common\Command\CommandBus:
        class: App\Infrastructure\Common\Command\MessengerCommandBus

    App\Infrastructure\Common\Query\QueryBus:
        class: App\Infrastructure\Common\Query\MessengerQueryBus

    api_exception_subscriber:
        class: App\Infrastructure\ApiExceptionSubscriber
        arguments: [ ]
        tags:
            - { name: kernel.event_subscriber }

    Psr\Log\LoggerInterface:
        class: Monolog\Logger
        arguments:
            $name: 'monolog'

    App\Infrastructure\Common\Event\Publisher: ~
    App\Infrastructure\Common\Event\Subscriber: ~
    App\Domain\Card\PaginationService: ~

    #Controllers
    App\Application\Catalog\CardController: ~
    App\Application\Deck\DeckController: ~

    #Repositories
    App\Infrastructure\Common\Event\EventRepository:
        class: App\Infrastructure\Common\Event\EventRepository
    App\Infrastructure\Card\CardRepository:
        class: App\Infrastructure\Card\CardRepository
    App\Infrastructure\Card\WrapperRepository:
        class: App\Infrastructure\Card\WrapperRepository
        arguments:
            $cardRepository: '@App\Infrastructure\Card\CardRepository'
            $eventRepository: '@App\Infrastructure\Common\Event\EventRepository'
            $publisher: '@App\Infrastructure\Common\Event\Publisher'
    App\Infrastructure\Deck\DeckRepository:
        class: App\Infrastructure\Deck\DeckRepository
        arguments:
            $deckCardRepository: '@App\Infrastructure\Deck\Card\DeckCardRepository'
    App\Infrastructure\Deck\WrapperRepository:
        class: App\Infrastructure\Deck\WrapperRepository
        arguments:
            $deckRepository: '@App\Infrastructure\Deck\DeckRepository'
            $eventRepository: '@App\Infrastructure\Common\Event\EventRepository'
            $publisher: '@App\Infrastructure\Common\Event\Publisher'
    App\Infrastructure\Deck\Card\DeckCardRepository:
        class: App\Infrastructure\Deck\Card\DeckCardRepository

    #Validators
    App\Infrastructure\Card\ValidatorInterface:
        class: App\Infrastructure\Card\Validator
    App\Infrastructure\Deck\ValidatorInterface:
        class: App\Infrastructure\Deck\Validator

    #Generators
    App\Infrastructure\Common\Generator\GeneratorInterface:
        class: App\Infrastructure\Common\Generator\UuidGenerator

    #Command Handlers
    App\Domain\Card\Command\AddCardHandler:
        public: true
        class: App\Domain\Card\Command\AddCardHandler
        arguments:
            $repository: '@App\Infrastructure\Card\WrapperRepository'
        tags:
            - { name: command_handler, handles: App\Domain\Card\Command\AddCardCommand }
    App\Domain\Card\Command\DeleteCardHandler:
        public: true
        class: App\Domain\Card\Command\DeleteCardHandler
        arguments:
            $repository: '@App\Infrastructure\Card\WrapperRepository'
        tags:
            - { name: command_handler, handles: App\Domain\Card\Command\DeleteCardCommand }
    App\Domain\Card\Command\UpdateCardHandler:
        public: true
        class: App\Domain\Card\Command\UpdateCardHandler
        arguments:
            $repository: '@App\Infrastructure\Card\WrapperRepository'
        tags:
            - { name: command_handler, handles: App\Domain\Card\Command\UpdateCardCommand }

    App\Domain\Deck\Command\AddDeckHandler:
        public: true
        class: App\Domain\Deck\Command\AddDeckHandler
        arguments:
            $repository: '@App\Infrastructure\Deck\WrapperRepository'
        tags:
            - { name: command_handler, handles: App\Domain\Deck\Command\AddDeckCommand }
    App\Domain\Deck\Command\AddDeckCardHandler:
        public: true
        class: App\Domain\Deck\Command\AddDeckCardHandler
        arguments:
            $repository: '@App\Infrastructure\Deck\WrapperRepository'
            $cardRepository: '@App\Infrastructure\Card\CardRepository'
        tags:
            - { name: command_handler, handles: App\Domain\Deck\Command\AddDeckCardCommand }

    #Query Handlers
    App\Domain\Card\Query\GetCardHandler:
        public: true
        class: App\Domain\Card\Query\GetCardHandler
        arguments:
            $repository: '@App\Infrastructure\Card\WrapperRepository'
        tags:
            - { name: command_handler, bus: query.bus, handles: App\Domain\Card\Query\GetCardQuery }
    App\Domain\Card\Query\GetCardListHandler:
        public: true
        class: App\Domain\Card\Query\GetCardListHandler
        arguments:
            $repository: '@App\Infrastructure\Card\WrapperRepository'
            $paginationService: '@App\Domain\Card\PaginationService'
        tags:
            - { name: command_handler, bus: query.bus, handles: App\Domain\Card\Query\GetCardListQuery }
    App\Domain\Deck\Query\GetDeckHandler:
        public: true
        class: App\Domain\Deck\Query\GetDeckHandler
        arguments:
            $repository: '@App\Infrastructure\Deck\WrapperRepository'
        tags:
            - { name: command_handler, bus: query.bus, handles: App\Domain\Deck\Query\GetDeckQuery }