# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    _instanceof:
        App\Infrastructure\Common\Command\CommandHandler:
            tags:
                - { name: messenger.message_handler, bus: command.bus }
        App\Infrastructure\Common\Query\QueryHandler:
            tags:
                - { name: messenger.message_handler, bus: query.bus }

    App\Infrastructure\Common\Command\CommandBus:
        class: App\Infrastructure\Common\Command\MessengerCommandBus

    App\Infrastructure\Common\Query\QueryBus:
        class: App\Infrastructure\Common\Query\MessengerQueryBus

    Psr\Log\LoggerInterface:
        class: Monolog\Logger
        arguments:
            $name: 'monolog'

    #Controllers\
    App\Application\Catalog\CardController: ~

    #Handlers
    App\Domain\Card\Command\AddCardHandler:
        public: true
        class: App\Domain\Card\Command\AddCardHandler
        tags:
            - { name: command_handler, handles: App\Domain\Card\Command\AddCardCommand }

    #Repositories
    App\Domain\Card\CardRepositoryInterface:
        class: App\Infrastructure\Card\CardRepository
