# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        public: false

    App\Infrastructure\Common\Command\CommandBus:
        class: App\Infrastructure\Common\Command\MessengerCommandBus

    App\Infrastructure\Common\Query\QueryBus:
        class: App\Infrastructure\Common\Query\MessengerQueryBus

    api_exception_subscriber:
        class: App\Infrastructure\ApiExceptionSubscriber
        arguments: [ ]
        tags:
            - { name: kernel.event_subscriber }

    Psr\Log\LoggerInterface:
        class: Monolog\Logger
        arguments:
            $name: 'monolog'

    App\Infrastructure\Common\Event\Publisher: ~
    App\Infrastructure\Common\Event\Subscriber: ~
    App\Domain\Card\PaginationService: ~

    #Controllers
    App\Application\Catalog\CardController: ~
    App\Application\Deck\DeckController: ~

    #Repositories
    App\Infrastructure\Common\Event\EventRepository:
        class: App\Infrastructure\Common\Event\EventRepository
    App\Infrastructure\Card\CardRepository:
        class: App\Infrastructure\Card\CardRepository
    App\Infrastructure\Card\WrapperRepository:
        class: App\Infrastructure\Card\WrapperRepository
        arguments:
            $cardRepository: '@App\Infrastructure\Card\CardRepository'
            $eventRepository: '@App\Infrastructure\Common\Event\EventRepository'
            $publisher: '@App\Infrastructure\Common\Event\Publisher'
    App\Infrastructure\Deck\DeckRepository:
        class: App\Infrastructure\Deck\DeckRepository
        arguments:
            $deckCardRepository: '@App\Infrastructure\Deck\Card\DeckCardRepository'
    App\Infrastructure\Deck\WrapperRepository:
        class: App\Infrastructure\Deck\WrapperRepository
        arguments:
            $deckRepository: '@App\Infrastructure\Deck\DeckRepository'
            $eventRepository: '@App\Infrastructure\Common\Event\EventRepository'
            $publisher: '@App\Infrastructure\Common\Event\Publisher'
    App\Infrastructure\Deck\Card\DeckCardRepository:
        class: App\Infrastructure\Deck\Card\DeckCardRepository
        arguments:
            $cardRepository: '@App\Infrastructure\Card\CardRepository'

    #Validators
    App\Infrastructure\ValidatorInterface:
        class: App\Infrastructure\Validator

    #Generators
    App\Infrastructure\Common\Generator\GeneratorInterface:
        class: App\Infrastructure\Common\Generator\UuidGenerator

    _instanceof:
        App\Infrastructure\Common\Command\CommandHandler:
            tags:
                - { name: messenger.message_handler, bus: command.bus }
        App\Infrastructure\Common\Query\QueryHandler:
            tags:
                - { name: messenger.message_handler, bus: query.bus }

    #Query handlers
    card_query_handlers:
        namespace: App\Domain\Card\Query\
        resource: '../src/Domain/Card/Query/*Handler.php'
        autoconfigure: false
        arguments:
            $repository: '@App\Infrastructure\Card\WrapperRepository'
    deck_query_handlers:
        namespace: App\Domain\Deck\Query\
        resource: '../src/Domain/Deck/Query/*Handler.php'
        autoconfigure: false
        arguments:
            $repository: '@App\Infrastructure\Deck\WrapperRepository'

    #Command handlers
    card_command_handlers:
        namespace: App\Domain\Card\Command\
        resource: '../src/Domain/Card/Command/*Handler.php'
        autoconfigure: false
        arguments:
            $repository: '@App\Infrastructure\Card\WrapperRepository'
    deck_command_handlers:
        namespace: App\Domain\Deck\Command\
        resource: '../src/Domain/Deck/Command/*Handler.php'
        autoconfigure: false
        arguments:
            $repository: '@App\Infrastructure\Deck\WrapperRepository'
            $cardRepository: '@App\Infrastructure\Card\CardRepository'
    App\Domain\Deck\Command\AddDeckHandler:
        public: true
        class: App\Domain\Deck\Command\AddDeckHandler
        arguments:
            $repository: '@App\Infrastructure\Deck\WrapperRepository'
